{"who_uses_software": "Retreat centers across the globe. ", "cat_name": "Yoga Studio", "vendor_name": "Retreat Guru", "product_name": "Retreat Booking Guru", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Gyms and health clubs of any size, studios, group fitness, single site & multi site facilities and franchises.", "cat_name": "Yoga Studio", "vendor_name": "treshna Enterprises", "product_name": "GymMaster", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Reservio is optimized for 70 different business categories from healthcare, personal care, sport and education.", "cat_name": "Yoga Studio", "vendor_name": "Reservio", "product_name": "Reservio", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Offices, co-working spaces, universities, sports venues, studios & churches are just some of the places that manage the use of their rooms, courts, studios, halls and all other 'spaces' with Skedda.", "cat_name": "Yoga Studio", "vendor_name": "Skedda", "product_name": "Skedda Bookings", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "ClubManager works with Gyms, MMA's, Gymnastics, Personal Trainers, Bootcamps, Dance schools, Football & Rugby and Leisure Centres. ", "cat_name": "Yoga Studio", "vendor_name": "ClubManager", "product_name": "ClubManager", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Square", "product_name": "Square Card Reader", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "This software was designed specifically for Yoga Teachers.", "cat_name": "Yoga Studio", "vendor_name": "YogaClassPlan", "product_name": "YogaClassPlan.com", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Yoga Instructors, Yoga Instructors in Training, Yoga Studio Owners", "cat_name": "Yoga Studio", "vendor_name": "Tummee", "product_name": "Yoga Sequence Builder", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Yoga studios and independent yoga instructors", "cat_name": "Yoga Studio", "vendor_name": "Trillo", "product_name": "Punchpass", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "TripleThreat Software", "product_name": "Studio Manager", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Studio and school administrators. Music, art, yoga, dance, language, martial arts, and more.", "cat_name": "Yoga Studio", "vendor_name": "Studio Helper", "product_name": "Studio Helper", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Sports\r\nFitness\r\nWellness\r\nGroup Management\r\nKid's Camps", "cat_name": "Yoga Studio", "vendor_name": "Omnify", "product_name": "Omnify", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "GreenRope", "product_name": "MyYogaConnection", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "yoga studio, dance studio, pilates studio", "cat_name": "Yoga Studio", "vendor_name": "My Best Studio Software", "product_name": "My Best Studio Software", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Internetopolis", "product_name": "YogaSite", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Platypus Software", "product_name": "EZeMember", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Momoyoga", "product_name": "Momoyoga", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Dharma Tribe", "product_name": "Dharma Tribe - Yoga", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Our main market includes dance studios in the United States of America. Secondarily, we market to martial arts and yoga studios.", "cat_name": "Yoga Studio", "vendor_name": "Compete Services", "product_name": "Compete Services", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Recreational Solutions", "product_name": "ClassTrack", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Designed specifically for class oriented businesses, such as dance, martial arts, music studios, pre-schools/daycares, as well as gyms, hockey, yoga, fitness centers and talent agencies.", "cat_name": "Yoga Studio", "vendor_name": "Halcyon Logic Solutions", "product_name": "ClassMate", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Freelance, Appointment-based business, Medical Practitioner, Consultants", "cat_name": "Yoga Studio", "vendor_name": "Artichoke", "product_name": "Artichoke", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Subway Solutions", "product_name": "Yoga Sage", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Subway Solutions", "product_name": "Yoga Sage", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Subway Solutions", "product_name": "Yoga Sage", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Subway Solutions", "product_name": "Yoga Sage", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Subway Solutions", "product_name": "Yoga Sage", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "HealingRadiusPro satiates to the Wellness Center Owners and also Independent Therapists who provide Wellness and Healing Solutions to the Wellness Community. ", "cat_name": "Yoga Studio", "vendor_name": "HealingRadius", "product_name": "HealingRadiusPro", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Akada Software", "product_name": "DanceWorks", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Class based businesses use iClassPro to streamline daily activities, registration, improve communications and boost productivity in the workplace. Accessible online, it's great for on-the-go business.", "cat_name": "Yoga Studio", "vendor_name": "iClassPro", "product_name": "iClassPro", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Ideal for Gyms, Fitness Centers, Yoga Studios, Martial Art Studios, Dance Studios, Fitness Clinics, Fitness Lounge, Pilates Studios, Recreational Clubs, Sports Clubs, Spas & Salons", "cat_name": "Yoga Studio", "vendor_name": "Grip Technologies", "product_name": "FitnessForce", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Yoga and Pilates studios, Crossfit and Fitness gyms around the world. Great UI, automations and integrated marketing.", "cat_name": "Yoga Studio", "vendor_name": "Karmasoft", "product_name": "Karmasoft ", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": null, "cat_name": "Yoga Studio", "vendor_name": "Bookeo", "product_name": "Bookeo", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
{"who_uses_software": "Accommodation businesses that also manage activities and/or rentals. Such as surf and yoga retreats, camps, lodges, schools, package holiday providers, holiday directories. ", "cat_name": "Yoga Studio", "vendor_name": "Bookinglayer", "product_name": "Bookinglayer", "profile_link": "http://www.capterra.com/yoga-studio-software/spotlight/141414/YogaSite/Internetopolis", "cat_link": "http://www.capterra.com/yoga-studio-software/"}
